### PR TITLE
Feature: command /exclude & related functionality

### PR DESCRIPTION
**Pull request by veryipsum**
## Command overview (exclude.js):
`/exclude <arg1::String> <arg2::CSV>` expects two inputs (which it will sanitize): 
- The target username (can be a simple string or an @mention)
   This is used for retrieving the target user ID. The ID is used for verifications done in `/@exclude/check.js` and stored by `memdb`.
   When a string is provided as input a **fetch() query**[^1] is performed in the context of **the current guild**[^2].
   When using an @ mention; the command receives the target user ID and no further API calls are needed.
- A comma separated list of values that represent valid commands
   Valid commands represent **slash commands**[^3] that are registered by the bot.
   The sanitized CSV input (ex: `help, ping, spam`) will be verified against **Guild.commands**[^3]; commands not found in the registered array will be ignored.

If all inputs are sanitized and validated the command script will call `/@exclude/functions.js` > `addToExclusionList()`;

#### /@exclude/check.js
Used for adding conditional execution to commands.
It exports one function: `userIsAllowed(user::String, command::String):Boolean` which takes in two arguments and returns a Boolean:
- `user` represents the `memdb` stored user ID; expects type of **GuildMember.id**[^4]
- `command` represents the command executed by the user; expects type of **CommandInteraction.commandName**[^5]

If the input user exists in the `memdb` and it contains the executed command the return will be `False`, halting command propagation & execution. Response logic is handled separately.

image

#### /@exclude/functions.js
Contains logic required by the `/exclude` command; that is not directly needed in the command script, but instead needed for propagation of events that require other modules.

- `sanitizeInputs(user::String, commands::CSV, guild::Guild):Object`[^2]
   Responsible for cleaning up the inputs provided in the `/exclude` command; it will make further calls to 
   `/modules/disambiguate` > `userId()` & `csvArguments()` and will return an object containing the absolute **target user ID**[^4] 
   and a sanitized list of commands from the input.
- `addToExclusionList(arg1::Object, arg2::CommandInteraction):void`[^5]
   Responsible for committing the `/exclude` command arguments to the `memdb` cache and the related storage file. The object passed in the first argument contains the following attributes: `userId`[^4], validated `commands`[^3] from input;
   If the inputes are successfully validated the validated commands will be appended to the user entry in `memdb.cache` and committed to the storage file.

#### /modules/disambiguate
Provides functions for sanitizing inputs and general command arguments; can be used as dependency.
- `csvArguments(input::String):Array`
   Will sanitize the input string and will convert CSV to [JavaScript::Array()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array); does not provide a map. Will not traverse multi-dimensional CSVs/Arrays.
- `queryGuildForUser(username::String, guild::Guild):Promise)`[^2]
   Used to get an instance of **GuildMember**[^4] based on input `username` in the context of the provided `guild`. Will return a [JavaScript::Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) which should be resolved by the logic that invoked the call.
- `userId(input::String, guild::Guild`):String/Promise[^2]
   Used to either sanitize `/exclude` user input or to retrieve the **target user ID**[^4] via `queryGuildForUser()`. Returns a string of the member ID in the first case and a [JavaScript::Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) in the latter case.

#### /modules/memdb
Provides an interface to reading/writing to a storage cache/file. Permanent storage is saved to `./store/`.
All function instances will update an internal `cachedb` variable which is exported for global usage as `cache`. Its recommended that scripting logic is done firstly on the cache and committed to the permanent storage only when updating values.
- `write(filename::String, data::Object):void`
   Used for writing to the permanent storage. `filename` determines which storage file will be used for saving the `data` object.
- `read(filename::String):Object`
   Used for reading from a storage file. If the file provided by `filename` is not found it will be created at runtime. Will load the data retrieved from file to `cache` and then returned.

image

[^1]: [discord.js - GuildMemberManager](https://old.discordjs.dev/#/docs/discord.js/main/class/GuildMemberManager)
  [discord.js - GuildMemberManager.fetch()](https://old.discordjs.dev/#/docs/discord.js/main/class/GuildMemberManager?scrollTo=fetch)
[^2]: [discord.js - Guild](https://old.discordjs.dev/#/docs/discord.js/main/class/Guild)
[^3]: [discord.js - Guild.commands](https://old.discordjs.dev/#/docs/discord.js/main/class/Guild?scrollTo=commands)
[^4]: [discord.js - GuildMember.id](https://old.discordjs.dev/#/docs/discord.js/main/class/GuildMember?scrollTo=id)
[^5]: [discord.js - CommandInteraction](https://old.discordjs.dev/#/docs/discord.js/main/class/CommandInteraction)
 [discord.js - CommandInteraction.commandName](https://old.discordjs.dev/#/docs/discord.js/main/class/CommandInteraction?scrollTo=commandName)

### CODE REVIEW

**Comment by veryipsum** [comment]
@virlancristian feel free to review the changes & documentation.

**Comment by veryipsum** [comment]
Small FYI, this PR can be merged before PR #2 please see my latest feedback https://github.com/virlancristian/shaorma-bot/pull/2#issuecomment-1738132162. I think it will make adopting the suggested directory structure much easier on your branch. Let me know what you think.

**Comment by veryipsum** [comment]
@virlancristian as discussed; I have updated the implementation of the command execution permissions to be handled at interaction-level when any command is issued; part of commit [f671315](https://github.com/virlancristian/shaorma-bot/pull/3/commits/f671315cf49d2a73b9c26987aeaaaa258ad1ad7f).
As part of the same commit a missing logic check was added to the `exclude` command script (meant to add an exception to validating registered commands - "all" can be used as argument in the command to restrict a user from using all commands)

**Comment by veryipsum** [comment]
Added `member.permissions`[^1] verification on `/exclude` as this command is not meant for all users; part of commit [1d33549](https://github.com/virlancristian/shaorma-bot/pull/3/commits/1d33549af08a5aa5719d7560d6ba8772cd023c52).

[^1]: discord.js - [GuildMember.permissions](https://old.discordjs.dev/#/docs/discord.js/main/class/GuildMember?scrollTo=permissions)

**Review by virlancristian — APPROVED** [review]

**Pull request merged**
